Josh
jcgoble3/mrc-discord-bot pull request #31
Opened 2021-03-23 23:41 UTC by jluckenbill

Added a proof of concept function in support of issue #26. See inline commenting for an understanding of the implementation.

2021-03-24 00:36 UTC, mdlubbers167 approved these changes, later dismissed
Looks good! I added an inline comment about the greeting after the user invokes the hello command. Also, the command should be renamed but it is just a proof of concept for now.

2021-03-24 00:36 UTC, mdlubbers167 commented on cogs/info.py
> +        await ctx.send(f"How are you today?")
does this create a greeting when the user types the hello command? Isn't the user already greeted when they enter the channel/when the bot joins the channel? This may not be necessary.

2021-03-24 04:39 UTC, jcgoble3 commented on cogs/info.py
> +        await ctx.send(f"How are you today?")
My feeling here is that this is more about the user saying hello to the bot. It's a command for when you're bored. :P

2021-03-24 05:03 UTC, jcgoble3 requested changes
Overall, the command works great. Comment style and not burning extra bytecode cycles is the main problem. Requested changes should be an easy fix.

2021-03-24 05:03 UTC, jcgoble3 commented on cogs/info.py
> +        """ These lines send the greeting """
Python's line comment character is `#`. Python does not have block comments *per se*.

While triple-quoted strings can be used to simulate block comments (which can be useful while debugging to disable a section of code), using them as general-purpose comments (excluding docstrings, described below) is discouraged for two reasons. First, they are not ignored by the compiler, and produce two bytecodes (LOAD_CONST and POP_TOP) that slow down code execution by a tiny amount.

Second, when the first statement in a function, method, or class is a lone string literal expression statement, that string becomes the *docstring* for it and is stored in an attribute of the function/method/class object. Docstrings are used in several places in the language for introspection and documentation, and the Discord library we are using additionally uses the first line of a command's docstring as the help text for the command. If you run the bot with this code and enter `!help`, it will DM you a list of commands. Toward the bottom, you will see this:
```
Information:
  about        About the bot 
  botserver    Get an invite to our support server! 
  hello        These lines send the greeting 
```
Notice that since this string is the first statement in the function, it becomes the docstring and the Discord library uses this string as help text, which isn't correct. So here you should convert this comment to regular comment syntax (by placing `#` before the comment), and add a short docstring for use with the `!help` command, something like the attached suggestion.
```suggestion
    async def hello(self, ctx):
        """Greet the user and ask them how their day is."""
        # These lines send the greeting
```

2021-03-24 05:03 UTC, jcgoble3 commented on cogs/info.py
> +            message the wait_for function is looking for is returned """
See above.
```suggestion
        # The purpose of the check function is to filter out messages so that only the
        # message the wait_for function is looking for is returned
```

2021-03-24 05:03 UTC, jcgoble3 commented on cogs/info.py
> +                to the channel, informing the user by name, that they took to long to respond. """
```suggestion
            # This line waits for a response from the user. The wait period times out
            # after 10 seconds. When a timeout occurs, an asyncio.TimeoutError execption
            # is thrown. This execption is caught on the next line and a response is sent
            # to the channel, informing the user by name, that they took to long to respond.
```

2021-03-24 05:03 UTC, jcgoble3 commented on cogs/info.py
> +            msg = await self.bot.wait_for('message', timeout=10.0, check=check)
I did run your code and check with my second account, and it does correctly ignore other users and still receive the original author's reply. It also correctly handles two users using the command at the same time with overlapping "conversations" in one channel.

2021-03-24 05:03 UTC, jcgoble3 commented on cogs/info.py
> +            """ These lines customize the bot's response based on user input. """
```suggestion
            # These lines customize the bot's response based on user input.
```

2021-03-24 05:03 UTC, jcgoble3 commented on cogs/info.py
> +            """ check that the channel is the same between the message and the context """
```suggestion
            # check that the channel is the same between the message and the context
```

2021-03-24 05:03 UTC, jcgoble3 commented on cogs/info.py
> +            """ check that the author is the same between the message and the context """
```suggestion
            # check that the author is the same between the message and the context
```

2021-04-01 23:33 UTC, jluckenbill commented on cogs/info.py
> +        await ctx.send(f"How are you today?")
Yes. this creates a greeting when the user types !hello. It may be redundant in a practical sense, it was just a proof of concept.

2021-04-01 23:35 UTC, jluckenbill commented on cogs/info.py
> +            msg = await self.bot.wait_for('message', timeout=10.0, check=check)
Nice, thanks

2021-04-01 23:37 UTC, jluckenbill reviewed
I applied the suggested changes

2021-04-01 23:39 UTC, jcgoble3 approved these changes
All good, feel free to merge.

2021-04-01 23:40 UTC, merged

2021-04-17 01:30 UTC, dward118 commented on cogs/info.py
> +
The "bad", "good", and "great" isn't as descriptive as it could be but is fine for now.